s = set()

n = int(input("enter the number 1 : "))
s.add(n)
n = int(input("enter the number 2 : "))
s.add(n)
n = int(input("enter the number 3 : "))
s.add(n)
n = int(input("enter the number 4 : "))
s.add(n)
n = int(input("enter the number 5 : "))
s.add(n)
n = int(input("enter the number 6 : "))
s.add(n)
n = int(input("enter the number 7 : "))
s.add(n)
n = int(input("enter the number 8 : "))
s.add(n)

print(s)    